/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintStationRouteImport } from './routes/print-station'
import { Route as MiFotoTokenRouteImport } from './routes/mi-foto.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintStationRoute = PrintStationRouteImport.update({
  id: '/print-station',
  path: '/print-station',
  getParentRoute: () => rootRouteImport,
} as any)
const MiFotoTokenRoute = MiFotoTokenRouteImport.update({
  id: '/mi-foto/$token',
  path: '/mi-foto/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/print-station': typeof PrintStationRoute
  '/mi-foto/$token': typeof MiFotoTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/print-station': typeof PrintStationRoute
  '/mi-foto/$token': typeof MiFotoTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/print-station': typeof PrintStationRoute
  '/mi-foto/$token': typeof MiFotoTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/print-station' | '/mi-foto/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/print-station' | '/mi-foto/$token'
  id: '__root__' | '/' | '/print-station' | '/mi-foto/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrintStationRoute: typeof PrintStationRoute
  MiFotoTokenRoute: typeof MiFotoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-station': {
      id: '/print-station'
      path: '/print-station'
      fullPath: '/print-station'
      preLoaderRoute: typeof PrintStationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-foto/$token': {
      id: '/mi-foto/$token'
      path: '/mi-foto/$token'
      fullPath: '/mi-foto/$token'
      preLoaderRoute: typeof MiFotoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrintStationRoute: PrintStationRoute,
  MiFotoTokenRoute: MiFotoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
